app = 'gi-playground'
primary_region = 'ams'

[build]

[deploy]
  strategy = 'immediate'

[env]
  GI_PLAYGROUND_ENV = 'production'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    grace_period = '10s'
    interval = '30s'
    method = 'GET'
    path = '/api/version'
    timeout = '5s'

[mounts]
  source = 'gi_data'
  destination = '/data'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
